# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-03 23:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.IntegerField(blank=True)),
                ('alumno', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to='personas.Alumno')),
                ('clase', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to='cursos.Clase')),
                ('curso', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to='cursos.Curso')),
            ],
        ),
    ]
