# Generated by Django 2.0.7 on 2018-09-14 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(max_length=30)),
                ('modulo', models.IntegerField(blank=True)),
                ('fechaI', models.DateField(max_length=50)),
                ('fechaF', models.DateField(max_length=50)),
                ('profesorID', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to='personas.Profesor')),
            ],
        ),
    ]
