# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-03 23:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
        ('computadoras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aula', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to='cursos.Aula')),
                ('computadoras', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to='computadoras.Computadora')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('horario', models.IntegerField(blank=True)),
                ('cantidad', models.IntegerField(blank=True)),
                ('profesor', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to='personas.Profesor')),
            ],
        ),
    ]
