# Generated by Django 2.1.1 on 2019-02-20 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='anio',
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='alumnoID',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='personas.Alumno'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='cursoID',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='cursos.Curso'),
        ),
    ]
