# Generated by Django 2.1.1 on 2018-09-18 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_auto_20180918_1447'),
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('alumnoID', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to='personas.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='curso',
            name='fechaF',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='fechaI',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='materia',
        ),
        migrations.AddField(
            model_name='curso',
            name='anio',
            field=models.IntegerField(blank=True, default=2018),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='estado',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='mes',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asistencia',
            name='cursoID',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to='cursos.Curso'),
        ),
        migrations.AddField(
            model_name='curso',
            name='materiaID',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to='cursos.Materia'),
        ),
    ]
