# Generated by Django 2.1.1 on 2019-02-20 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dependencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='dependenciaId',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='dependencia.Dependencia'),
        ),
        migrations.AlterField(
            model_name='dependencia',
            name='telefono',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='dependencia',
            name='whatsapp',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='detalleaula',
            name='aulaId',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='dependencia.Aula'),
        ),
    ]
