# Generated by Django 2.0.7 on 2018-09-12 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dependencia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleAula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aulaId', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to='dependencia.Aula')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleHorario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='dia',
            name='aulaId',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='diaId',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='estado',
        ),
        migrations.AddField(
            model_name='detallehorario',
            name='aulaId',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to='dependencia.Dia'),
        ),
        migrations.AddField(
            model_name='detallehorario',
            name='horaId',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to='dependencia.Horario'),
        ),
        migrations.AddField(
            model_name='detalleaula',
            name='diaId',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to='dependencia.Dia'),
        ),
    ]
