# Generated by Django 2.0.7 on 2018-09-14 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dependencia', '0002_auto_20180912_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallehorario',
            name='aulaId',
        ),
        migrations.RemoveField(
            model_name='detallehorario',
            name='horaId',
        ),
        migrations.AddField(
            model_name='detalleaula',
            name='estado',
            field=models.CharField(default='disponible', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detalleaula',
            name='horaId',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to='dependencia.Horario'),
        ),
        migrations.DeleteModel(
            name='DetalleHorario',
        ),
    ]
