# Generated by Django 2.0.7 on 2018-09-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependencia', '0004_detalleaula_cursoid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dependencia',
            name='direccion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dependencia',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dia',
            name='dia',
            field=models.CharField(max_length=15),
        ),
    ]
