# Generated by Django 2.0.7 on 2018-10-25 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dependencia', '0005_auto_20180914_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleaula',
            name='cursoID',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='cursos.Curso'),
        ),
    ]
