# Generated by Django 2.1.1 on 2018-11-26 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('dni', models.IntegerField(blank=True)),
                ('mail', models.EmailField(max_length=30)),
                ('telefono', models.IntegerField(blank=True)),
                ('nacimiento', models.DateField()),
                ('titulo', models.CharField(max_length=30)),
                ('trabajo', models.BooleanField(default=True)),
                ('dispHoraria', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('dni', models.IntegerField(blank=True)),
                ('mail', models.EmailField(max_length=30)),
                ('telefono', models.IntegerField(blank=True)),
                ('nacimiento', models.DateField()),
                ('titulo', models.CharField(max_length=30)),
                ('expediente', models.IntegerField(blank=True)),
                ('estudiosId', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to='personas.Estudio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='alumno',
            name='estudiosId',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to='personas.Estudio'),
        ),
    ]
