# Generated by Django 2.1.1 on 2018-09-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('dni', models.IntegerField(blank=True)),
                ('email', models.EmailField(max_length=30)),
                ('telefono', models.IntegerField(blank=True)),
                ('nacimiento', models.DateField()),
                ('trabajo', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('dni', models.IntegerField(blank=True)),
                ('email', models.EmailField(max_length=30)),
                ('telefono', models.IntegerField(blank=True)),
                ('nacimiento', models.DateField()),
                ('legajo', models.IntegerField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
