# Generated by Django 2.1.1 on 2018-09-18 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='alumno',
            old_name='email',
            new_name='mail',
        ),
        migrations.RenameField(
            model_name='profesor',
            old_name='legajo',
            new_name='expediente',
        ),
        migrations.RenameField(
            model_name='profesor',
            old_name='email',
            new_name='mail',
        ),
        migrations.AddField(
            model_name='alumno',
            name='dispHoraria',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumno',
            name='titulo',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profesor',
            name='titulo',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumno',
            name='estudiosId',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to='personas.Estudio'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='estudiosId',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to='personas.Estudio'),
        ),
    ]
