# Generated by Django 2.1.1 on 2018-09-21 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_auto_20180918_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='tipo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profesor',
            name='tipo',
            field=models.BooleanField(default=True),
        ),
    ]
