# Generated by Django 2.0.7 on 2018-09-26 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_auto_20180920_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='tipo',
        ),
    ]
